create table "public"."action_groups" (
    "id" bigint generated by default as identity not null,
    "key" text,
    "actions" jsonb[],
    "created_at" timestamp with time zone not null default now()
);


create table "public"."assistants" (
    "id" text not null,
    "data" jsonb,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."integrations" (
    "id" bigint generated by default as identity not null,
    "type" text,
    "data" jsonb,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."threads" (
    "id" text not null,
    "messages" jsonb[],
    "data" jsonb,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."triggers" (
    "id" bigint generated by default as identity not null,
    "type" text,
    "created_at" timestamp with time zone not null default now(),
    "data" jsonb
);


alter table "public"."flows" add column "components" jsonb[];

CREATE UNIQUE INDEX assistants_pkey ON public.assistants USING btree (id);

CREATE UNIQUE INDEX integrations_pkey ON public.integrations USING btree (id);

CREATE UNIQUE INDEX pages_pkey ON public.action_groups USING btree (id);

CREATE UNIQUE INDEX pages_url_key ON public.action_groups USING btree (key);

CREATE UNIQUE INDEX threads_pkey ON public.threads USING btree (id);

CREATE UNIQUE INDEX triggers_pkey ON public.triggers USING btree (id);

alter table "public"."action_groups" add constraint "pages_pkey" PRIMARY KEY using index "pages_pkey";

alter table "public"."assistants" add constraint "assistants_pkey" PRIMARY KEY using index "assistants_pkey";

alter table "public"."integrations" add constraint "integrations_pkey" PRIMARY KEY using index "integrations_pkey";

alter table "public"."threads" add constraint "threads_pkey" PRIMARY KEY using index "threads_pkey";

alter table "public"."triggers" add constraint "triggers_pkey" PRIMARY KEY using index "triggers_pkey";

alter table "public"."action_groups" add constraint "pages_url_key" UNIQUE using index "pages_url_key";

grant delete on table "public"."action_groups" to "anon";

grant insert on table "public"."action_groups" to "anon";

grant references on table "public"."action_groups" to "anon";

grant select on table "public"."action_groups" to "anon";

grant trigger on table "public"."action_groups" to "anon";

grant truncate on table "public"."action_groups" to "anon";

grant update on table "public"."action_groups" to "anon";

grant delete on table "public"."action_groups" to "authenticated";

grant insert on table "public"."action_groups" to "authenticated";

grant references on table "public"."action_groups" to "authenticated";

grant select on table "public"."action_groups" to "authenticated";

grant trigger on table "public"."action_groups" to "authenticated";

grant truncate on table "public"."action_groups" to "authenticated";

grant update on table "public"."action_groups" to "authenticated";

grant delete on table "public"."action_groups" to "service_role";

grant insert on table "public"."action_groups" to "service_role";

grant references on table "public"."action_groups" to "service_role";

grant select on table "public"."action_groups" to "service_role";

grant trigger on table "public"."action_groups" to "service_role";

grant truncate on table "public"."action_groups" to "service_role";

grant update on table "public"."action_groups" to "service_role";

grant delete on table "public"."assistants" to "anon";

grant insert on table "public"."assistants" to "anon";

grant references on table "public"."assistants" to "anon";

grant select on table "public"."assistants" to "anon";

grant trigger on table "public"."assistants" to "anon";

grant truncate on table "public"."assistants" to "anon";

grant update on table "public"."assistants" to "anon";

grant delete on table "public"."assistants" to "authenticated";

grant insert on table "public"."assistants" to "authenticated";

grant references on table "public"."assistants" to "authenticated";

grant select on table "public"."assistants" to "authenticated";

grant trigger on table "public"."assistants" to "authenticated";

grant truncate on table "public"."assistants" to "authenticated";

grant update on table "public"."assistants" to "authenticated";

grant delete on table "public"."assistants" to "service_role";

grant insert on table "public"."assistants" to "service_role";

grant references on table "public"."assistants" to "service_role";

grant select on table "public"."assistants" to "service_role";

grant trigger on table "public"."assistants" to "service_role";

grant truncate on table "public"."assistants" to "service_role";

grant update on table "public"."assistants" to "service_role";

grant delete on table "public"."integrations" to "anon";

grant insert on table "public"."integrations" to "anon";

grant references on table "public"."integrations" to "anon";

grant select on table "public"."integrations" to "anon";

grant trigger on table "public"."integrations" to "anon";

grant truncate on table "public"."integrations" to "anon";

grant update on table "public"."integrations" to "anon";

grant delete on table "public"."integrations" to "authenticated";

grant insert on table "public"."integrations" to "authenticated";

grant references on table "public"."integrations" to "authenticated";

grant select on table "public"."integrations" to "authenticated";

grant trigger on table "public"."integrations" to "authenticated";

grant truncate on table "public"."integrations" to "authenticated";

grant update on table "public"."integrations" to "authenticated";

grant delete on table "public"."integrations" to "service_role";

grant insert on table "public"."integrations" to "service_role";

grant references on table "public"."integrations" to "service_role";

grant select on table "public"."integrations" to "service_role";

grant trigger on table "public"."integrations" to "service_role";

grant truncate on table "public"."integrations" to "service_role";

grant update on table "public"."integrations" to "service_role";

grant delete on table "public"."threads" to "anon";

grant insert on table "public"."threads" to "anon";

grant references on table "public"."threads" to "anon";

grant select on table "public"."threads" to "anon";

grant trigger on table "public"."threads" to "anon";

grant truncate on table "public"."threads" to "anon";

grant update on table "public"."threads" to "anon";

grant delete on table "public"."threads" to "authenticated";

grant insert on table "public"."threads" to "authenticated";

grant references on table "public"."threads" to "authenticated";

grant select on table "public"."threads" to "authenticated";

grant trigger on table "public"."threads" to "authenticated";

grant truncate on table "public"."threads" to "authenticated";

grant update on table "public"."threads" to "authenticated";

grant delete on table "public"."threads" to "service_role";

grant insert on table "public"."threads" to "service_role";

grant references on table "public"."threads" to "service_role";

grant select on table "public"."threads" to "service_role";

grant trigger on table "public"."threads" to "service_role";

grant truncate on table "public"."threads" to "service_role";

grant update on table "public"."threads" to "service_role";

grant delete on table "public"."triggers" to "anon";

grant insert on table "public"."triggers" to "anon";

grant references on table "public"."triggers" to "anon";

grant select on table "public"."triggers" to "anon";

grant trigger on table "public"."triggers" to "anon";

grant truncate on table "public"."triggers" to "anon";

grant update on table "public"."triggers" to "anon";

grant delete on table "public"."triggers" to "authenticated";

grant insert on table "public"."triggers" to "authenticated";

grant references on table "public"."triggers" to "authenticated";

grant select on table "public"."triggers" to "authenticated";

grant trigger on table "public"."triggers" to "authenticated";

grant truncate on table "public"."triggers" to "authenticated";

grant update on table "public"."triggers" to "authenticated";

grant delete on table "public"."triggers" to "service_role";

grant insert on table "public"."triggers" to "service_role";

grant references on table "public"."triggers" to "service_role";

grant select on table "public"."triggers" to "service_role";

grant trigger on table "public"."triggers" to "service_role";

grant truncate on table "public"."triggers" to "service_role";

grant update on table "public"."triggers" to "service_role";